-- ============================================================
-- rebuild_all.sql — full schema, migrations 001 → 007 concatenated (DEVELOPMENT ONLY)
--
-- GENERATED by scripts/db.mjs — do not hand-edit. Change a migration in
-- supabase/migrations/ and run `npm run db:bundle` (or db:rebuild/db:fresh,
-- which regenerate this automatically). Run after reset_dev.sql to rebuild
-- the entire schema in one pass.
-- ============================================================


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- BEGIN 001_foundation.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- 001 — Foundation: Auth, Institutions & Membership
--
-- Consolidated schema (dev phase — drop & recreate). This is the
-- FINAL state of every object below; there are no later
-- CREATE OR REPLACE chains to replay.
--
-- Tables : institutions, profiles, institution_members,
--          institution_allowed_emails
-- Helpers: get_my_institution_ids, is_admin_of,
--          generate_institution_code, next_student_code
-- RPCs   : is_email_allowed, is_institution_name_available,
--          link_user_to_institution
-- Trigger: handle_new_user (on auth.users)
-- ============================================================


-- ============================================================
-- 1. TABLES
-- ============================================================

CREATE TABLE public.institutions (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name                TEXT        NOT NULL,
  slug                TEXT        NOT NULL,
  code                TEXT,                       -- short human prefix for student codes (e.g. "MVA")
  student_seq         INT         NOT NULL DEFAULT 0,  -- atomic per-institution student counter
  logo_url            TEXT,
  category            TEXT,
  address             TEXT,
  contact_email       TEXT,
  contact_mobile      TEXT,
  programs            TEXT[]      DEFAULT '{}',
  timezone            TEXT        DEFAULT 'Asia/Kolkata',
  plan                TEXT        DEFAULT 'free'
                                  CHECK (plan IN ('free', 'pro', 'enterprise')),
  sms_credits         INT         DEFAULT 0,
  working_hours       JSONB       DEFAULT '{}',
  fee_config          JSONB       DEFAULT '{}',
  onboarding_complete BOOLEAN     DEFAULT false,
  created_at          TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT institutions_name_unique UNIQUE (name),
  CONSTRAINT institutions_slug_unique UNIQUE (slug)
);

-- One row per person regardless of how many institutions they belong to.
-- Role lives in institution_members, not here.
CREATE TABLE public.profiles (
  id         UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email      TEXT        NOT NULL,
  full_name  TEXT,
  mobile     TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Join table: one row per (user, institution) pair.
CREATE TABLE public.institution_members (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id)  ON DELETE CASCADE,
  user_id        UUID        NOT NULL REFERENCES public.profiles(id)       ON DELETE CASCADE,
  role           TEXT        NOT NULL CHECK (role IN ('admin', 'coach', 'student')),
  status         TEXT        DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at     TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT institution_members_unique UNIQUE (institution_id, user_id)
);

-- Admin pre-approves emails before the user signs up.
-- Unique constraint enforces the "email + institution must be unique" rule.
CREATE TABLE public.institution_allowed_emails (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id)  ON DELETE CASCADE,
  email          TEXT        NOT NULL,
  role           TEXT        NOT NULL CHECK (role IN ('student', 'coach')),
  added_by       UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  status         TEXT        DEFAULT 'pending' CHECK (status IN ('pending', 'joined')),
  created_at     TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT institution_allowed_emails_unique UNIQUE (institution_id, email)
);


-- ============================================================
-- 2. INDEXES
-- ============================================================

CREATE INDEX idx_institutions_slug
  ON public.institutions (slug);

-- Institution code is globally unique (it prefixes every student code).
CREATE UNIQUE INDEX idx_institutions_code_unique
  ON public.institutions (code)
  WHERE code IS NOT NULL;

CREATE INDEX idx_profiles_email
  ON public.profiles (email);

CREATE INDEX idx_institution_members_user_id
  ON public.institution_members (user_id);

CREATE INDEX idx_institution_members_institution_id
  ON public.institution_members (institution_id);

CREATE INDEX idx_allowed_emails_email
  ON public.institution_allowed_emails (email);

CREATE INDEX idx_allowed_emails_institution_id
  ON public.institution_allowed_emails (institution_id);

-- Partial index — only pending rows are queried by the trigger
CREATE INDEX idx_allowed_emails_pending
  ON public.institution_allowed_emails (email)
  WHERE status = 'pending';


-- ============================================================
-- 3. HELPER FUNCTIONS (bypass RLS — used inside RLS policies
--    to avoid infinite recursion on institution_members)
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_my_institution_ids()
RETURNS UUID[]
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT ARRAY(
    SELECT institution_id
    FROM   public.institution_members
    WHERE  user_id = auth.uid()
      AND  status  = 'active'
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin_of(p_institution_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM   public.institution_members
    WHERE  institution_id = p_institution_id
      AND  user_id        = auth.uid()
      AND  role           = 'admin'
      AND  status         = 'active'
  );
$$;


-- ============================================================
-- 4. PUBLIC RPCs (SECURITY DEFINER, called pre-auth)
--
-- is_email_allowed / is_institution_name_available run for
-- unauthenticated visitors at register/signup time, so they must
-- bypass RLS. Each returns only a boolean — no row data leaks.
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_email_allowed(p_email TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM   public.institution_allowed_emails
    WHERE  lower(email)  = lower(p_email)
      AND  status        = 'pending'
  );
$$;

-- Case-insensitive + trimmed so it matches the institutions_name_unique
-- behaviour the user actually hits on signup.
CREATE OR REPLACE FUNCTION public.is_institution_name_available(p_name TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT NOT EXISTS (
    SELECT 1
    FROM   public.institutions
    WHERE  lower(name) = lower(trim(p_name))
  );
$$;


-- ============================================================
-- 5. STUDENT-CODE HELPERS
--
-- Each institution gets a short CODE (initials of its name). Every
-- student gets a globally-unique student_code = CODE || zero-padded
-- per-institution sequence (e.g. MVA0007), which lets a synthetic
-- login email be built from the code alone.
-- ============================================================

-- SECURITY DEFINER so the unauthenticated /register flow can preview
-- the code before the account exists.
CREATE OR REPLACE FUNCTION public.generate_institution_code(p_name TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_words     TEXT[];
  v_word      TEXT;
  v_base      TEXT := '';
  v_candidate TEXT;
  v_suffix    INT  := 1;
BEGIN
  -- Split the uppercased name into alphabetic words (drop digits/punctuation).
  v_words := regexp_split_to_array(upper(coalesce(p_name, '')), '[^A-Z]+');

  -- Base = initials of each word (e.g. "Mira Volley Academy" -> "MVA").
  FOREACH v_word IN ARRAY v_words LOOP
    IF length(v_word) > 0 THEN
      v_base := v_base || left(v_word, 1);
    END IF;
  END LOOP;

  -- Fewer than 3 initials (e.g. a single-word name): pad from its letters.
  IF length(v_base) < 3 THEN
    v_base := left(array_to_string(v_words, ''), 3);
  ELSE
    v_base := left(v_base, 3);
  END IF;

  -- No usable letters at all -> deterministic fallback; always 3 chars.
  IF length(v_base) = 0 THEN
    v_base := 'ACA';
  END IF;
  v_base := rpad(v_base, 3, 'X');

  -- Bare base first, then append an incrementing suffix until unique.
  v_candidate := v_base;
  WHILE EXISTS (SELECT 1 FROM public.institutions WHERE code = v_candidate) LOOP
    v_suffix    := v_suffix + 1;
    v_candidate := v_base || v_suffix::TEXT;
  END LOOP;

  RETURN v_candidate;
END;
$$;

-- Admin-only. UPDATE ... RETURNING locks the institution row, so
-- concurrent "Add Student" / imports never collide.
CREATE OR REPLACE FUNCTION public.next_student_code(p_institution_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code TEXT;
  v_seq  INT;
BEGIN
  IF NOT public.is_admin_of(p_institution_id) THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;

  UPDATE public.institutions
  SET    student_seq = student_seq + 1
  WHERE  id = p_institution_id
  RETURNING code, student_seq INTO v_code, v_seq;

  -- Institution has no code yet — assign one now.
  IF v_code IS NULL THEN
    v_code := public.generate_institution_code(
      (SELECT name FROM public.institutions WHERE id = p_institution_id)
    );
    UPDATE public.institutions SET code = v_code WHERE id = p_institution_id;
  END IF;

  RETURN v_code || lpad(v_seq::TEXT, 4, '0');
END;
$$;


-- ============================================================
-- 6. ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.institutions               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.institution_members        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.institution_allowed_emails ENABLE ROW LEVEL SECURITY;

-- institutions
CREATE POLICY "members can read their institution"
  ON public.institutions FOR SELECT
  USING (id = ANY(public.get_my_institution_ids()));

CREATE POLICY "admins can update their institution"
  ON public.institutions FOR UPDATE
  USING (public.is_admin_of(id));

-- profiles
CREATE POLICY "users can read own profile"
  ON public.profiles FOR SELECT
  USING (id = auth.uid());

CREATE POLICY "members of shared institution can read each other"
  ON public.profiles FOR SELECT
  USING (
    id IN (
      SELECT user_id
      FROM   public.institution_members
      WHERE  institution_id = ANY(public.get_my_institution_ids())
    )
  );

CREATE POLICY "users can update own profile"
  ON public.profiles FOR UPDATE
  USING (id = auth.uid());

-- institution_members
CREATE POLICY "members can view their institution roster"
  ON public.institution_members FOR SELECT
  USING (institution_id = ANY(public.get_my_institution_ids()));

CREATE POLICY "admins can add members"
  ON public.institution_members FOR INSERT
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins can update member status"
  ON public.institution_members FOR UPDATE
  USING (public.is_admin_of(institution_id));

CREATE POLICY "admins can remove members"
  ON public.institution_members FOR DELETE
  USING (public.is_admin_of(institution_id));

-- institution_allowed_emails
CREATE POLICY "admins can view allowed emails"
  ON public.institution_allowed_emails FOR SELECT
  USING (public.is_admin_of(institution_id));

CREATE POLICY "admins can add allowed emails"
  ON public.institution_allowed_emails FOR INSERT
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins can update allowed emails"
  ON public.institution_allowed_emails FOR UPDATE
  USING (public.is_admin_of(institution_id));

CREATE POLICY "admins can delete allowed emails"
  ON public.institution_allowed_emails FOR DELETE
  USING (public.is_admin_of(institution_id));


-- ============================================================
-- 7. TRIGGER — handle new user signup
--
-- Fires on every auth.users INSERT. Branches on
-- raw_user_meta_data.signup_type:
--
--   'institution_admin' → create institution (+ code) + profile
--                          + admin member row
--   'student'           → create profile + auto-link via
--                          allowed_emails (case-insensitive)
--   'student_code'      → only the profile row is created here;
--                          membership is inserted by the app via
--                          the service-role admin client.
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_signup_type      TEXT;
  v_institution_name TEXT;
  v_institution_slug TEXT;
  v_institution_code TEXT;
  v_category         TEXT;
  v_new_institution  UUID;
  v_allowed          RECORD;
  v_constraint       TEXT;
  v_linked           INT;
BEGIN
  v_signup_type := NEW.raw_user_meta_data->>'signup_type';

  -- Always create the profile row first
  INSERT INTO public.profiles (id, email, full_name, mobile)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'mobile'
  );

  IF v_signup_type = 'institution_admin' THEN

    v_institution_name := NEW.raw_user_meta_data->>'institution_name';
    v_institution_slug := NEW.raw_user_meta_data->>'institution_slug';
    v_category         := NEW.raw_user_meta_data->>'category';
    v_institution_code := NEW.raw_user_meta_data->>'institution_code';

    -- The app previews a code, but generate one if absent.
    IF v_institution_code IS NULL OR length(v_institution_code) = 0 THEN
      v_institution_code := public.generate_institution_code(v_institution_name);
    END IF;

    BEGIN
      INSERT INTO public.institutions
             (name, slug, category, contact_email, contact_mobile, code)
      VALUES (v_institution_name, v_institution_slug, v_category,
              NEW.email, NEW.raw_user_meta_data->>'mobile', v_institution_code)
      RETURNING id INTO v_new_institution;
    EXCEPTION WHEN unique_violation THEN
      GET STACKED DIAGNOSTICS v_constraint = CONSTRAINT_NAME;
      IF v_constraint = 'idx_institutions_code_unique' THEN
        -- Rare race: the previewed code was taken between preview and insert.
        -- Regenerate a fresh, unique code and retry once.
        v_institution_code := public.generate_institution_code(v_institution_name);
        INSERT INTO public.institutions
               (name, slug, category, contact_email, contact_mobile, code)
        VALUES (v_institution_name, v_institution_slug, v_category,
                NEW.email, NEW.raw_user_meta_data->>'mobile', v_institution_code)
        RETURNING id INTO v_new_institution;
      ELSE
        -- The academy NAME or SLUG is already taken (institutions_name_unique /
        -- institutions_slug_unique). Regenerating the code wouldn't help, so
        -- raise a clean, app-recognisable error instead of retrying into the
        -- same collision. The app re-checks the name pre-signup; this is the
        -- backstop for the race.
        RAISE EXCEPTION 'institution_name_taken'
          USING ERRCODE = 'unique_violation';
      END IF;
    END;

    INSERT INTO public.institution_members (institution_id, user_id, role)
    VALUES (v_new_institution, NEW.id, 'admin');

  ELSIF v_signup_type = 'student' THEN

    -- Link to every institution that pre-approved this email (case-insensitive)
    v_linked := 0;
    FOR v_allowed IN
      SELECT id, institution_id, role
      FROM   public.institution_allowed_emails
      WHERE  lower(email) = lower(NEW.email)
        AND  status = 'pending'
    LOOP
      INSERT INTO public.institution_members (institution_id, user_id, role)
      VALUES (v_allowed.institution_id, NEW.id, v_allowed.role)
      ON CONFLICT (institution_id, user_id) DO NOTHING;

      UPDATE public.institution_allowed_emails
      SET    status = 'joined'
      WHERE  id     = v_allowed.id;

      v_linked := v_linked + 1;
    END LOOP;

    -- Invite-only enforcement. The app checks is_email_allowed before signup,
    -- but the publishable key lets anyone call auth.signUp directly with an
    -- arbitrary signup_type, so the real gate must live here: abort (rolling
    -- back the auth.users insert) when the email was never pre-approved.
    IF v_linked = 0 THEN
      RAISE EXCEPTION 'email_not_allowed'
        USING ERRCODE = 'check_violation';
    END IF;

  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- 8. RPC — link_user_to_institution
--
-- Called from the app when an admin adds an email. If the account
-- already exists it is linked immediately; otherwise the email is
-- whitelisted and the trigger links it on signup. All email
-- comparisons are case-insensitive.
-- ============================================================

CREATE OR REPLACE FUNCTION public.link_user_to_institution(
  p_institution_id UUID,
  p_email          TEXT,
  p_role           TEXT,
  p_added_by       UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_profile_id UUID;
  v_result     JSONB;
BEGIN
  -- Caller must be an admin of this institution
  IF NOT public.is_admin_of(p_institution_id) THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;

  SELECT id INTO v_profile_id
  FROM   public.profiles
  WHERE  lower(email) = lower(p_email);

  IF v_profile_id IS NOT NULL THEN
    -- Account exists → link immediately
    INSERT INTO public.institution_members (institution_id, user_id, role)
    VALUES (p_institution_id, v_profile_id, p_role)
    ON CONFLICT (institution_id, user_id) DO NOTHING;

    INSERT INTO public.institution_allowed_emails
           (institution_id, email, role, added_by, status)
    VALUES (p_institution_id, lower(p_email), p_role, p_added_by, 'joined')
    ON CONFLICT (institution_id, email)
    DO UPDATE SET status   = 'joined',
                  role     = EXCLUDED.role,
                  added_by = EXCLUDED.added_by;

    v_result := jsonb_build_object('linked', true, 'status', 'joined');
  ELSE
    -- No account yet → add to whitelist; trigger links them on signup
    INSERT INTO public.institution_allowed_emails
           (institution_id, email, role, added_by, status)
    VALUES (p_institution_id, lower(p_email), p_role, p_added_by, 'pending')
    ON CONFLICT (institution_id, email)
    DO UPDATE SET role     = EXCLUDED.role,
                  added_by = EXCLUDED.added_by;

    v_result := jsonb_build_object('linked', false, 'status', 'pending');
  END IF;

  RETURN v_result;
END;
$$;


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- BEGIN 002_coaches.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- 002 — Coach Management
-- The `coaches` coaching-profile extension table.
--
-- A `coaches` row is NOT an identity — it extends an existing
-- institution_members row (role='coach') with coaching-specific
-- attributes (programs, availability, calendar colour).
-- Active/inactive status lives in institution_members.status,
-- NOT here, so there is one source of truth.
-- ============================================================


-- ============================================================
-- 1. TABLE
-- ============================================================

CREATE TABLE public.coaches (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  user_id        UUID        NOT NULL REFERENCES public.profiles(id)     ON DELETE CASCADE,
  programs       TEXT[]      DEFAULT '{}',
  -- { "mon": [{ "start": "06:00", "end": "09:00" }], "tue": [], ... }
  availability   JSONB       DEFAULT '{}',
  color          TEXT,                      -- hex colour for the calendar lane (Module 6)
  bio            TEXT,
  joined_at      DATE        DEFAULT now(),
  created_at     TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT coaches_institution_user_unique UNIQUE (institution_id, user_id)
);

CREATE INDEX idx_coaches_institution_id
  ON public.coaches (institution_id);


-- ============================================================
-- 2. HELPER FUNCTION
--    Mirrors is_admin_of / get_my_institution_ids in 001.
--    SECURITY DEFINER so it can be called inside RLS policies
--    without recursing on institution_members.
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_coach_of(p_institution_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM   public.institution_members
    WHERE  institution_id = p_institution_id
      AND  user_id        = auth.uid()
      AND  role           = 'coach'
      AND  status         = 'active'
  );
$$;


-- ============================================================
-- 3. ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.coaches ENABLE ROW LEVEL SECURITY;

-- Any active member of the institution can read its coaches.
CREATE POLICY "members can read coaches"
  ON public.coaches FOR SELECT
  USING (institution_id = ANY(public.get_my_institution_ids()));

-- Admins manage anyone; a coach may create their OWN row (first
-- self-service availability save) when they are a coach here.
CREATE POLICY "admins or self can insert coach"
  ON public.coaches FOR INSERT
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR (user_id = auth.uid() AND public.is_coach_of(institution_id))
  );

-- Admins update anyone; a coach updates only their own row. WITH CHECK mirrors
-- USING so the row can't be re-pointed at another user_id on update (without an
-- explicit WITH CHECK, Postgres reuses USING — make it explicit so it survives
-- future policy edits).
CREATE POLICY "admins or self can update coach"
  ON public.coaches FOR UPDATE
  USING (
    public.is_admin_of(institution_id)
    OR user_id = auth.uid()
  )
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR user_id = auth.uid()
  );

-- Only admins delete (rare — prefer membership soft-delete).
CREATE POLICY "admins can delete coach"
  ON public.coaches FOR DELETE
  USING (public.is_admin_of(institution_id));


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- BEGIN 003_students.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- 003 — Student Management
-- The `students` table: academy-owned records, NOT logins.
--
-- A student is a profile OWNED by the institution, decoupled from
-- auth identity. Under-14 kids have no email; a parent enrols
-- multiple siblings under the SAME parent_email (no unique
-- constraint). The two nullable FKs (user_id, parent_user_id)
-- ship now but stay NULL until the 14+ login / parent portal land.
--
-- student_code = institution code + per-institution sequence
-- (e.g. MVA0007), generated via next_student_code() in 001. It is
-- globally unique so a synthetic login email can be built from the
-- code alone — no academy selector at login.
-- ============================================================


-- ============================================================
-- 1. TABLE
-- ============================================================

CREATE TABLE public.students (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id   UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  student_code     TEXT,                                   -- academy roll number (auto-generated)
  full_name        TEXT        NOT NULL,
  calling_name     TEXT,
  dob              DATE        NOT NULL,
  gender           TEXT        CHECK (gender IN ('male', 'female', 'other')),
  parent_name      TEXT        NOT NULL,
  parent_mobile    TEXT        NOT NULL,                   -- E.164, e.g. +919876543210
  parent_email     TEXT,                                   -- plain contact — NO unique constraint
  programs         TEXT[]      DEFAULT '{}',
  enrolment_date   DATE        DEFAULT now(),
  status           TEXT        DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  photo_url        TEXT,                                   -- column ships; upload wired later
  uniform_size     TEXT,
  uniform_number   INT,
  uniform_name     TEXT,
  monthly_fee      INT,                                    -- recurring monthly fee, in paise
  deposit_amount   INT,                                    -- one-time advance / deposit, in paise
  sms_opt_in       BOOLEAN     DEFAULT true,
  user_id          UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,  -- 14+ own login (NULL now)
  parent_user_id   UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,  -- parent portal (NULL now)
  created_at       TIMESTAMPTZ DEFAULT now()
);


-- ============================================================
-- 2. INDEXES
-- ============================================================

-- Hard key: ONLY student_code, and only when present (partial unique).
-- The single collision-free key an admin controls; also the dedup key
-- for any future CSV re-import.
CREATE UNIQUE INDEX idx_students_code_unique
  ON public.students (institution_id, student_code)
  WHERE student_code IS NOT NULL;

-- Global unique student_code (case-insensitive) — lets the synthetic
-- login email be built from the code alone. Lower() matches Supabase's
-- lowercased emails.
CREATE UNIQUE INDEX idx_students_code_global_unique
  ON public.students (lower(student_code))
  WHERE student_code IS NOT NULL;

-- Duplicate DETECTION key (non-unique) — case-insensitive name + dob.
-- NOT a UNIQUE constraint: names collide (common names, twins) and a hard
-- key would reject legitimate students. Soft detection + admin confirm.
CREATE INDEX idx_students_dupe
  ON public.students (institution_id, lower(full_name), dob);

CREATE INDEX idx_students_institution_status
  ON public.students (institution_id, status);


-- ============================================================
-- 3. ROW LEVEL SECURITY
--    Reuses the 001 helpers (get_my_institution_ids / is_admin_of)
--    so policies never recurse on institution_members.
-- ============================================================

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- Any active member of the institution (admin or coach) reads the roster.
-- The self/guardian clauses are forward-compatible: the future 14+ student
-- and parent-portal logins read their own rows with no new migration.
CREATE POLICY "members read students"
  ON public.students FOR SELECT
  USING (
    institution_id = ANY(public.get_my_institution_ids())
    OR user_id        = auth.uid()
    OR parent_user_id = auth.uid()
  );

-- Only admins create / edit / delete students (deletes rare — prefer the
-- soft-delete via status = 'inactive').
CREATE POLICY "admins insert students"
  ON public.students FOR INSERT
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins update students"
  ON public.students FOR UPDATE
  USING (public.is_admin_of(institution_id));

CREATE POLICY "admins delete students"
  ON public.students FOR DELETE
  USING (public.is_admin_of(institution_id));


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- BEGIN 004_batches.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- 004 — Batch Management
-- `batches` (training groups) + `batch_students` (enrolment join).
--
-- A batch is a scheduled training group owned by the institution and
-- (optionally) assigned to a coach. Coaches CONTROL their own batches:
-- a coach can create/edit/manage enrolment for batches where they are
-- the assigned coach; admins manage every batch in the institution.
--
-- Occurrences are NOT stored — the schedule (a per-day JSONB slot array
-- + effective_from) is the source of truth; the calendar computes
-- occurrences on the fly (Module 6).
-- ============================================================


-- ============================================================
-- 1. TABLES
-- ============================================================

CREATE TABLE public.batches (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  name           TEXT        NOT NULL,
  program        TEXT        NOT NULL,
  -- nullable: a batch may be created before a coach is assigned. ON DELETE
  -- SET NULL so removing a coach profile never deletes their batches.
  coach_id       UUID        REFERENCES public.coaches(id) ON DELETE SET NULL,
  -- Per-day timetable, one slot per day:
  --   [{ "day": 5, "start": "17:00", "end": "18:30" }, … ]
  -- where `day` is a JS Date.getDay() index (0 = Sun … 6 = Sat) so the
  -- occurrence/calendar math (Module 6) computes directly. `end > start` is
  -- validated in the server action (parseForm), not as a DB constraint.
  schedule       JSONB       NOT NULL DEFAULT '[]'::jsonb,
  venue          TEXT,
  capacity       INT         NOT NULL CHECK (capacity > 0),  -- max ACTIVE enrolments
  monthly_fee    INT         NOT NULL DEFAULT 0,             -- in paise
  status         TEXT        NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  effective_from DATE        NOT NULL DEFAULT now(),         -- first occurrence date
  created_at     TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_batches_institution_coach_status
  ON public.batches (institution_id, coach_id, status);


CREATE TABLE public.batch_students (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  -- institution_id is denormalised from batches so RLS policies don't have to
  -- join through batches on every row (mirrors the SELECT key on every tenant
  -- table). Kept consistent by the server actions.
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  batch_id       UUID        NOT NULL REFERENCES public.batches(id)  ON DELETE CASCADE,
  student_id     UUID        NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  status         TEXT        NOT NULL DEFAULT 'active'
                             CHECK (status IN ('active', 'waitlisted', 'dropped')),
  enrolled_at    TIMESTAMPTZ DEFAULT now(),                 -- waitlist promotion order
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- A student can be active/waitlisted in a batch at most once, but a dropped
-- row may coexist with a fresh re-enrolment (partial unique excludes dropped).
CREATE UNIQUE INDEX idx_batch_students_unique_active
  ON public.batch_students (batch_id, student_id)
  WHERE status <> 'dropped';

-- Active-count + waitlist-head lookups.
CREATE INDEX idx_batch_students_batch_status
  ON public.batch_students (batch_id, status, enrolled_at);


-- ============================================================
-- 2. HELPER FUNCTION
--    True when the given coaches.id row belongs to the caller.
--    SECURITY DEFINER so it can be used inside RLS policies without
--    recursing on coaches' own policies.
-- ============================================================

CREATE OR REPLACE FUNCTION public.owns_batch_coach(p_coach_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM   public.coaches
    WHERE  id      = p_coach_id
      AND  user_id = auth.uid()
  );
$$;


-- ============================================================
-- 3. ROW LEVEL SECURITY — batches
--    Admins manage all; coaches manage the batches assigned to them.
-- ============================================================

ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;

-- Any active member of the institution can read the batch list.
CREATE POLICY "members read batches"
  ON public.batches FOR SELECT
  USING (institution_id = ANY(public.get_my_institution_ids()));

-- Admins create any batch; a coach may create a batch only with coach_id
-- pointing at their OWN coaches row.
CREATE POLICY "admins or owning coach insert batches"
  ON public.batches FOR INSERT
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR (public.is_coach_of(institution_id) AND public.owns_batch_coach(coach_id))
  );

-- Admins update any batch; the assigned coach updates their own. WITH CHECK
-- mirrors USING so a coach can't re-point a batch at another coach.
CREATE POLICY "admins or owning coach update batches"
  ON public.batches FOR UPDATE
  USING (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(coach_id)
  )
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(coach_id)
  );

-- Only admins hard-delete (UI soft-deletes via status = 'inactive').
CREATE POLICY "admins delete batches"
  ON public.batches FOR DELETE
  USING (public.is_admin_of(institution_id));


-- ============================================================
-- 4. ROW LEVEL SECURITY — batch_students
--    Admins and the owning coach manage enrolment for a batch.
-- ============================================================

ALTER TABLE public.batch_students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "members read batch_students"
  ON public.batch_students FOR SELECT
  USING (institution_id = ANY(public.get_my_institution_ids()));

CREATE POLICY "admins or owning coach insert batch_students"
  ON public.batch_students FOR INSERT
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(
         (SELECT coach_id FROM public.batches WHERE id = batch_id)
       )
  );

CREATE POLICY "admins or owning coach update batch_students"
  ON public.batch_students FOR UPDATE
  USING (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(
         (SELECT coach_id FROM public.batches WHERE id = batch_id)
       )
  )
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(
         (SELECT coach_id FROM public.batches WHERE id = batch_id)
       )
  );

CREATE POLICY "admins or owning coach delete batch_students"
  ON public.batch_students FOR DELETE
  USING (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(
         (SELECT coach_id FROM public.batches WHERE id = batch_id)
       )
  );


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- BEGIN 005_sessions.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- 005 — 1-to-1 Sessions (Module 6: Calendar & Scheduling)
--
-- A `session` is a single dated coach↔student appointment (private
-- coaching), distinct from a batch occurrence. Batch occurrences are
-- still computed on the fly from `batches.schedule` (never stored);
-- only these 1-to-1 sessions persist.
--
-- Coaches CONTROL their own sessions: a coach can create/edit sessions
-- where they are the assigned coach; admins manage every session in the
-- institution. `end_time > start_time` is enforced in the server action
-- (parseForm), mirroring the per-day batch schedule convention — the
-- shape is validated application-side, not as a DB CHECK.
--
-- `fee_override` (paise, NULL = use the default/batch rate) is read by
-- Module 7 (Fee Management) when billing private sessions.
-- ============================================================


-- ============================================================
-- 1. TABLE
-- ============================================================

CREATE TABLE public.sessions (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  coach_id       UUID        NOT NULL REFERENCES public.coaches(id)      ON DELETE CASCADE,
  student_id     UUID        NOT NULL REFERENCES public.students(id)     ON DELETE CASCADE,
  date           DATE        NOT NULL,
  start_time     TIME        NOT NULL,
  end_time       TIME        NOT NULL,
  venue          TEXT,
  fee_override   INT,                                   -- in paise; NULL = use default rate
  status         TEXT        NOT NULL DEFAULT 'scheduled'
                             CHECK (status IN ('scheduled', 'completed', 'cancelled', 'no_show')),
  notes          TEXT,                                  -- coach notes after the session
  created_at     TIMESTAMPTZ DEFAULT now()
);

-- Calendar range scans are keyed by (institution, coach, date); the
-- student index backs per-student schedule + conflict lookups.
CREATE INDEX idx_sessions_institution_coach_date
  ON public.sessions (institution_id, coach_id, date);

CREATE INDEX idx_sessions_student_date
  ON public.sessions (student_id, date);


-- ============================================================
-- 2. ROW LEVEL SECURITY — sessions
--    Admins manage all; coaches manage the sessions assigned to them.
--    Mirrors the batches policies; reuses owns_batch_coach(coach_id),
--    which simply checks the coaches row belongs to auth.uid().
-- ============================================================

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Any active member of the institution can read sessions. The page
-- further scopes what each role sees (coach → own; student → own).
CREATE POLICY "members read sessions"
  ON public.sessions FOR SELECT
  USING (institution_id = ANY(public.get_my_institution_ids()));

-- Admins create any session; a coach may create a session only with
-- coach_id pointing at their OWN coaches row.
CREATE POLICY "admins or owning coach insert sessions"
  ON public.sessions FOR INSERT
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR (public.is_coach_of(institution_id) AND public.owns_batch_coach(coach_id))
  );

-- Admins update any session; the assigned coach updates their own.
CREATE POLICY "admins or owning coach update sessions"
  ON public.sessions FOR UPDATE
  USING (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(coach_id)
  )
  WITH CHECK (
    public.is_admin_of(institution_id)
    OR public.owns_batch_coach(coach_id)
  );

-- Only admins hard-delete (cancellation is a status change, not a delete).
CREATE POLICY "admins delete sessions"
  ON public.sessions FOR DELETE
  USING (public.is_admin_of(institution_id));


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- BEGIN 006_fees.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- 006 — Fee Management (Module 7)
--
-- Turns the per-student `monthly_fee` (003_students) into a billing
-- loop: a monthly `fee_ledger` invoice per student, and `fee_payments`
-- recorded against it.
--
-- Billing basis is PER-STUDENT FLAT: one ledger row per
-- (institution, student, month_year), amount_due = students.monthly_fee.
-- Students with a null/zero monthly_fee are not billed. Generation is
-- idempotent via the (institution_id, student_id, month_year) unique key.
--
-- Money is INT paise everywhere. There is NO PDF receipt — payments get
-- a sequential `receipt_number` reference only (next_receipt_number RPC).
--
-- RLS: admins manage all fee rows; a student reads their OWN invoices and
-- payments (via students.user_id / parent_user_id, mirroring the students
-- self-read clause). Coaches have no fee access. Generation runs via the
-- service-role client (bypasses RLS), so the write policies stay admin-only.
-- ============================================================


-- ============================================================
-- 1. RECEIPT SEQUENCE — per-institution counter for receipt numbers
-- ============================================================

ALTER TABLE public.institutions
  ADD COLUMN receipt_seq INT NOT NULL DEFAULT 0;


-- ============================================================
-- 2. TABLES
-- ============================================================

CREATE TABLE public.fee_ledger (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  student_id     UUID        NOT NULL REFERENCES public.students(id)     ON DELETE CASCADE,
  batch_id       UUID        REFERENCES public.batches(id) ON DELETE SET NULL,  -- reserved (per-batch/1:1 billing); unused in v1
  month_year     DATE        NOT NULL,                              -- always the 1st of the billed month
  amount_due     INT         NOT NULL,                              -- in paise
  amount_paid    INT         NOT NULL DEFAULT 0,                    -- in paise
  balance        INT         GENERATED ALWAYS AS (amount_due - amount_paid) STORED,
  status         TEXT        NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending', 'partial', 'paid', 'waived')),
  due_date       DATE,
  notes          TEXT,
  created_at     TIMESTAMPTZ DEFAULT now(),

  -- Idempotency key: one invoice per student per month. Generation upserts
  -- against this and never duplicates or clobbers a paid invoice.
  CONSTRAINT fee_ledger_unique UNIQUE (institution_id, student_id, month_year)
);

CREATE TABLE public.fee_payments (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  ledger_id      UUID        NOT NULL REFERENCES public.fee_ledger(id)   ON DELETE CASCADE,
  student_id     UUID        NOT NULL REFERENCES public.students(id)     ON DELETE CASCADE,  -- denormalised for student-scoped reads
  amount         INT         NOT NULL CHECK (amount > 0),           -- in paise
  paid_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  payment_mode   TEXT        NOT NULL CHECK (payment_mode IN ('cash', 'upi', 'card', 'cheque')),
  receipt_number TEXT,                                             -- reference number only (no PDF)
  recorded_by    UUID        REFERENCES public.profiles(id) ON DELETE SET NULL,
  voided_at      TIMESTAMPTZ,                                      -- NULL = active; non-null = voided
  notes          TEXT,
  created_at     TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT fee_payments_receipt_unique UNIQUE (institution_id, receipt_number)
);


-- ============================================================
-- 3. INDEXES
-- ============================================================

-- Dashboard scans: outstanding / overdue for an institution by status + due date.
CREATE INDEX idx_fee_ledger_institution_status
  ON public.fee_ledger (institution_id, status, due_date);

-- Per-student ledger lookups (StudentDetail Fees tab, student My Fees).
CREATE INDEX idx_fee_ledger_student
  ON public.fee_ledger (student_id, month_year);

-- Payment history scans.
CREATE INDEX idx_fee_payments_institution_student
  ON public.fee_payments (institution_id, student_id, paid_at);


-- ============================================================
-- 4. RECEIPT NUMBER RPC
--
-- Admin-only. UPDATE ... RETURNING locks the institution row so concurrent
-- payment records never collide on a receipt number. Format:
--   <prefix>-<YYYY>-<seq4>   e.g.  RCP-2026-0042
-- prefix comes from institutions.fee_config->>'receipt_prefix' (default RCP).
-- ============================================================

CREATE OR REPLACE FUNCTION public.next_receipt_number(p_institution_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_seq    INT;
  v_prefix TEXT;
BEGIN
  IF NOT public.is_admin_of(p_institution_id) THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;

  UPDATE public.institutions
  SET    receipt_seq = receipt_seq + 1
  WHERE  id = p_institution_id
  RETURNING receipt_seq,
            COALESCE(NULLIF(fee_config->>'receipt_prefix', ''), 'RCP')
  INTO   v_seq, v_prefix;

  RETURN v_prefix || '-' || to_char(now(), 'YYYY') || '-' || lpad(v_seq::TEXT, 4, '0');
END;
$$;


-- ============================================================
-- 4b. PAYMENT RPCs — atomic record / void
--
-- The whole record-payment and void-payment operations run inside one locked
-- transaction so concurrent writes can't lose an update on amount_paid, and a
-- failed payment insert can't leave a receipt-number gap. Admin-guarded,
-- mirroring next_receipt_number.
-- ============================================================

CREATE OR REPLACE FUNCTION public.record_fee_payment(
  p_ledger_id   UUID,
  p_amount      INT,
  p_mode        TEXT,
  p_paid_at     TIMESTAMPTZ,
  p_notes       TEXT,
  p_recorded_by UUID
)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ledger   public.fee_ledger;
  v_receipt  TEXT;
  v_new_paid INT;
BEGIN
  -- Lock the invoice row so concurrent payments serialise here.
  SELECT * INTO v_ledger FROM public.fee_ledger WHERE id = p_ledger_id FOR UPDATE;
  IF v_ledger.id IS NULL OR NOT public.is_admin_of(v_ledger.institution_id) THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;
  IF v_ledger.status IN ('paid', 'waived') THEN
    RAISE EXCEPTION 'Invoice already %', v_ledger.status;
  END IF;
  IF p_amount <= 0 THEN
    RAISE EXCEPTION 'Invalid amount';
  END IF;
  IF p_amount > v_ledger.amount_due - v_ledger.amount_paid THEN
    RAISE EXCEPTION 'Amount exceeds the outstanding balance';
  END IF;

  v_receipt  := public.next_receipt_number(v_ledger.institution_id);
  v_new_paid := v_ledger.amount_paid + p_amount;

  INSERT INTO public.fee_payments (
    institution_id, ledger_id, student_id, amount, payment_mode,
    receipt_number, recorded_by, notes, paid_at
  ) VALUES (
    v_ledger.institution_id, v_ledger.id, v_ledger.student_id, p_amount, p_mode,
    v_receipt, p_recorded_by, p_notes, COALESCE(p_paid_at, now())
  );

  UPDATE public.fee_ledger
  SET amount_paid = v_new_paid,
      status      = CASE
                      WHEN v_new_paid >= amount_due THEN 'paid'
                      WHEN v_new_paid > 0           THEN 'partial'
                      ELSE 'pending'
                    END
  WHERE id = v_ledger.id;

  RETURN v_receipt;
END;
$$;


CREATE OR REPLACE FUNCTION public.void_fee_payment(p_payment_id UUID)
RETURNS UUID                                   -- student_id, for revalidation
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_pay    public.fee_payments;
  v_ledger public.fee_ledger;
BEGIN
  SELECT * INTO v_pay FROM public.fee_payments WHERE id = p_payment_id FOR UPDATE;
  IF v_pay.id IS NULL OR NOT public.is_admin_of(v_pay.institution_id) THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;
  IF v_pay.voided_at IS NOT NULL THEN
    RETURN v_pay.student_id;                    -- already voided: no-op
  END IF;

  UPDATE public.fee_payments SET voided_at = now() WHERE id = v_pay.id;

  -- Reverse the amount off the invoice, unless it has been waived.
  SELECT * INTO v_ledger FROM public.fee_ledger WHERE id = v_pay.ledger_id FOR UPDATE;
  IF v_ledger.id IS NOT NULL AND v_ledger.status <> 'waived' THEN
    UPDATE public.fee_ledger
    SET amount_paid = GREATEST(0, amount_paid - v_pay.amount),
        status      = CASE
                        WHEN GREATEST(0, amount_paid - v_pay.amount) >= amount_due THEN 'paid'
                        WHEN GREATEST(0, amount_paid - v_pay.amount) > 0           THEN 'partial'
                        ELSE 'pending'
                      END
    WHERE id = v_ledger.id;
  END IF;

  RETURN v_pay.student_id;
END;
$$;


-- ============================================================
-- 5. ROW LEVEL SECURITY
--    Admins manage all; students read their own. Reuses the 001 helpers
--    (is_admin_of / get_my_institution_ids) and the students self-read shape.
-- ============================================================

ALTER TABLE public.fee_ledger   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_payments ENABLE ROW LEVEL SECURITY;

-- fee_ledger -------------------------------------------------

-- Admins read every invoice; a student reads only their own (via the linked
-- students row). Coaches are intentionally excluded (no fee access).
CREATE POLICY "admins or own student read fee_ledger"
  ON public.fee_ledger FOR SELECT
  USING (
    public.is_admin_of(institution_id)
    OR EXISTS (
      SELECT 1 FROM public.students s
      WHERE  s.id = fee_ledger.student_id
        AND  (s.user_id = auth.uid() OR s.parent_user_id = auth.uid())
    )
  );

CREATE POLICY "admins insert fee_ledger"
  ON public.fee_ledger FOR INSERT
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins update fee_ledger"
  ON public.fee_ledger FOR UPDATE
  USING (public.is_admin_of(institution_id))
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins delete fee_ledger"
  ON public.fee_ledger FOR DELETE
  USING (public.is_admin_of(institution_id));

-- fee_payments -----------------------------------------------

CREATE POLICY "admins or own student read fee_payments"
  ON public.fee_payments FOR SELECT
  USING (
    public.is_admin_of(institution_id)
    OR EXISTS (
      SELECT 1 FROM public.students s
      WHERE  s.id = fee_payments.student_id
        AND  (s.user_id = auth.uid() OR s.parent_user_id = auth.uid())
    )
  );

CREATE POLICY "admins insert fee_payments"
  ON public.fee_payments FOR INSERT
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins update fee_payments"
  ON public.fee_payments FOR UPDATE
  USING (public.is_admin_of(institution_id))
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins delete fee_payments"
  ON public.fee_payments FOR DELETE
  USING (public.is_admin_of(institution_id));


-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- BEGIN 007_sms.sql
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- ============================================================
-- 007 — Messaging: SMS + WhatsApp (Module 8, final MVP module)
--
-- Lets an academy message parents fee reminders from the Fees dashboard
-- using editable per-academy templates, with a full send log. Each
-- student has a `contact_channel` preference (sms / whatsapp / both) that
-- routes every outbound message; the message layer is provider-agnostic
-- (mock by default).
--
-- `sms_templates` — editable message bodies per institution (seeded
--   with fee_reminder + payment_confirmation defaults).
-- `sms_logs` — one row per attempted send, per channel (resolved body
--   + channel + status).
--
-- Sending is metered against institutions.sms_credits (decrement, never
-- block — there's no top-up flow yet) via decrement_sms_credits(); each
-- message (a `both` student = 2) spends one credit. Routing is driven by
-- students.contact_channel; the legacy students.sms_opt_in is no longer
-- read by the send path.
--
-- DEFERRED (columns reserved): the HMAC delivery webhook updates
-- sms_logs.status/delivered_at/gateway_ref — not wired in v1.
--
-- RLS: admins manage all; a student reads their OWN log rows (via
-- students.user_id/parent_user_id), mirroring fee_ledger. Templates are
-- admin-only.
-- ============================================================

-- Per-student channel preference (routes all outbound messages). 'both' fans
-- out to SMS + WhatsApp; 'none' opts the parent out of all messaging (the
-- successor to the legacy students.sms_opt_in consent flag).
ALTER TABLE public.students
  ADD COLUMN contact_channel TEXT NOT NULL DEFAULT 'sms'
  CHECK (contact_channel IN ('sms', 'whatsapp', 'both', 'none'));

-- Carry existing consent forward: parents who had opted out of SMS keep that
-- opt-out under the new model, so this migration never starts messaging a
-- parent who previously declined.
UPDATE public.students SET contact_channel = 'none' WHERE sms_opt_in IS FALSE;


-- ============================================================
-- 1. TABLES
-- ============================================================

CREATE TABLE public.sms_templates (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  name           TEXT        NOT NULL,                  -- e.g. fee_reminder, payment_confirmation
  body           TEXT        NOT NULL,                  -- with {placeholder} tokens
  updated_at     TIMESTAMPTZ DEFAULT now(),

  CONSTRAINT sms_templates_unique UNIQUE (institution_id, name)
);

CREATE TABLE public.sms_logs (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id UUID        NOT NULL REFERENCES public.institutions(id) ON DELETE CASCADE,
  ledger_id      UUID        REFERENCES public.fee_ledger(id) ON DELETE SET NULL,  -- NULL for non-fee messages
  student_id     UUID        REFERENCES public.students(id)   ON DELETE SET NULL,
  mobile         TEXT        NOT NULL,                  -- E.164
  message        TEXT        NOT NULL,                  -- resolved body (after token substitution)
  channel        TEXT        NOT NULL DEFAULT 'sms'
                             CHECK (channel IN ('sms', 'whatsapp')),
  template_name  TEXT,
  gateway_ref    TEXT,                                  -- reserved: gateway message id (delivery webhook)
  status         TEXT        NOT NULL DEFAULT 'sent'
                             CHECK (status IN ('sent', 'delivered', 'failed')),
  sent_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  delivered_at   TIMESTAMPTZ                            -- reserved: populated by delivery webhook
);


-- ============================================================
-- 2. INDEXES
-- ============================================================

CREATE INDEX idx_sms_logs_institution_sent
  ON public.sms_logs (institution_id, sent_at DESC);

CREATE INDEX idx_sms_logs_student
  ON public.sms_logs (student_id, sent_at DESC);


-- ============================================================
-- 3. CREDIT DECREMENT RPC
--    Admin-only, atomic. Floors at 0 (decrement + warn, never block).
--    Mirrors next_receipt_number (006).
-- ============================================================

CREATE OR REPLACE FUNCTION public.decrement_sms_credits(
  p_institution_id UUID,
  p_count          INT
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_remaining INT;
BEGIN
  IF NOT public.is_admin_of(p_institution_id) THEN
    RAISE EXCEPTION 'Not authorised';
  END IF;

  UPDATE public.institutions
  SET    sms_credits = GREATEST(COALESCE(sms_credits, 0) - GREATEST(p_count, 0), 0)
  WHERE  id = p_institution_id
  RETURNING sms_credits INTO v_remaining;

  RETURN v_remaining;
END;
$$;


-- ============================================================
-- 4. DEFAULT TEMPLATE SEEDING
--    Existing institutions are backfilled now; future ones are seeded by
--    an AFTER INSERT trigger. (001 is frozen — seeding lives here.)
-- ============================================================

CREATE OR REPLACE FUNCTION public.seed_sms_templates()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.sms_templates (institution_id, name, body)
  VALUES
    (NEW.id, 'fee_reminder',
     'Hi {parent_name}, fees of Rs.{amount_due} for {student_name} ({batch_name}) for {month} are due by {due_date}. - {academy_name}'),
    (NEW.id, 'payment_confirmation',
     'Hi {parent_name}, payment of Rs.{amount_paid} for {student_name} received on {payment_date}. Receipt no: {receipt_number}. - {academy_name}')
  ON CONFLICT (institution_id, name) DO NOTHING;

  RETURN NEW;
END;
$$;

CREATE TRIGGER on_institution_seed_sms_templates
  AFTER INSERT ON public.institutions
  FOR EACH ROW EXECUTE FUNCTION public.seed_sms_templates();

-- Backfill existing institutions.
INSERT INTO public.sms_templates (institution_id, name, body)
SELECT id, 'fee_reminder',
       'Hi {parent_name}, fees of Rs.{amount_due} for {student_name} ({batch_name}) for {month} are due by {due_date}. - {academy_name}'
FROM   public.institutions
ON CONFLICT (institution_id, name) DO NOTHING;

INSERT INTO public.sms_templates (institution_id, name, body)
SELECT id, 'payment_confirmation',
       'Hi {parent_name}, payment of Rs.{amount_paid} for {student_name} received on {payment_date}. Receipt no: {receipt_number}. - {academy_name}'
FROM   public.institutions
ON CONFLICT (institution_id, name) DO NOTHING;


-- ============================================================
-- 5. ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.sms_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sms_logs      ENABLE ROW LEVEL SECURITY;

-- sms_templates — admins only ------------------------------

CREATE POLICY "admins read sms_templates"
  ON public.sms_templates FOR SELECT
  USING (public.is_admin_of(institution_id));

CREATE POLICY "admins insert sms_templates"
  ON public.sms_templates FOR INSERT
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins update sms_templates"
  ON public.sms_templates FOR UPDATE
  USING (public.is_admin_of(institution_id))
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins delete sms_templates"
  ON public.sms_templates FOR DELETE
  USING (public.is_admin_of(institution_id));

-- sms_logs — admins manage; students read their own --------

CREATE POLICY "admins or own student read sms_logs"
  ON public.sms_logs FOR SELECT
  USING (
    public.is_admin_of(institution_id)
    OR EXISTS (
      SELECT 1 FROM public.students s
      WHERE  s.id = sms_logs.student_id
        AND  (s.user_id = auth.uid() OR s.parent_user_id = auth.uid())
    )
  );

CREATE POLICY "admins insert sms_logs"
  ON public.sms_logs FOR INSERT
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins update sms_logs"
  ON public.sms_logs FOR UPDATE
  USING (public.is_admin_of(institution_id))
  WITH CHECK (public.is_admin_of(institution_id));

CREATE POLICY "admins delete sms_logs"
  ON public.sms_logs FOR DELETE
  USING (public.is_admin_of(institution_id));
