#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Dev database runner (DEVELOPMENT ONLY).
//
//   node scripts/db.mjs bundle    Regenerate supabase/rebuild_all.sql from the
//                                 migrations/ folder (no DB connection).
//   node scripts/db.mjs rebuild   Bundle, then apply the full schema (001…N).
//   node scripts/db.mjs reset     Drop & recreate the public schema.
//   node scripts/db.mjs clear      Truncate every table, keep the schema.
//   node scripts/db.mjs fresh     reset + rebuild — wipe and recreate in one go.
//
// Everything except `bundle` shells out to `psql` using DATABASE_URL from
// .env.local. Get that string from the Supabase dashboard →
//   Project Settings → Database → Connection string → URI
// Use the SESSION pooler or the direct connection (NOT the transaction pooler
// on :6543 — it can't run the schema DDL). Add it to .env.local as:
//   DATABASE_URL=postgresql://postgres:<pwd>@<host>:5432/postgres
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const supa = join(root, 'supabase')
const migrationsDir = join(supa, 'migrations')
const bundlePath = join(supa, 'rebuild_all.sql')

const fail = (msg) => {
  console.error(`\n✖ ${msg}\n`)
  process.exit(1)
}

// --- .env.local loader (no dependency; never overrides a real env var) -------
function loadEnvLocal() {
  const file = join(root, '.env.local')
  if (!existsSync(file)) return
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = /^\s*([\w.]+)\s*=\s*(.*)\s*$/.exec(line)
    if (!m || line.trimStart().startsWith('#')) continue
    const key = m[1]
    let val = m[2].trim()
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1)
    }
    if (process.env[key] === undefined) process.env[key] = val
  }
}

// --- bundle: concatenate migrations/NNN_*.sql in order -----------------------
function migrationFiles() {
  return readdirSync(migrationsDir)
    .filter((f) => /^\d+.*\.sql$/.test(f))
    .sort()
}

function bundle() {
  const files = migrationFiles()
  if (files.length === 0) fail('No migration files found in supabase/migrations/.')

  const banner = (f) =>
    '\n\n-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n' +
    `-- BEGIN ${f}\n` +
    '-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n\n'

  const head =
    '-- ============================================================\n' +
    `-- rebuild_all.sql — full schema, migrations ${files[0].slice(0, 3)} → ` +
    `${files[files.length - 1].slice(0, 3)} concatenated (DEVELOPMENT ONLY)\n` +
    '--\n' +
    '-- GENERATED by scripts/db.mjs — do not hand-edit. Change a migration in\n' +
    '-- supabase/migrations/ and run `npm run db:bundle` (or db:rebuild/db:fresh,\n' +
    '-- which regenerate this automatically). Run after reset_dev.sql to rebuild\n' +
    '-- the entire schema in one pass.\n' +
    '-- ============================================================\n'

  const body = files.map((f) => banner(f) + readFileSync(join(migrationsDir, f), 'utf8')).join('')
  writeFileSync(bundlePath, head + body)
  console.log(`✔ Bundled ${files.length} migration(s) → supabase/rebuild_all.sql`)
  return files
}

// --- psql runner -------------------------------------------------------------
function runSql(relPaths) {
  const url = process.env.DATABASE_URL
  if (!url) {
    fail(
      'DATABASE_URL is not set. Add it to .env.local from the Supabase dashboard\n' +
        '  (Project Settings → Database → Connection string → URI, session/direct).\n' +
        '  Or paste the SQL files into the Supabase SQL editor by hand.'
    )
  }
  // Supabase requires TLS; default it unless the URL already specifies sslmode.
  const env = { ...process.env }
  if (!/sslmode=/.test(url) && !env.PGSSLMODE) env.PGSSLMODE = 'require'

  for (const rel of relPaths) {
    const file = join(supa, rel)
    console.log(`\n▶ psql -f supabase/${rel}`)
    const res = spawnSync('psql', [url, '-v', 'ON_ERROR_STOP=1', '-f', file], {
      stdio: 'inherit',
      env,
    })
    if (res.error?.code === 'ENOENT') {
      fail(
        'psql was not found on PATH. Install the PostgreSQL client tools, or\n' +
          '  paste supabase/' +
          rel +
          ' into the Supabase SQL editor instead.'
      )
    }
    if (res.status !== 0) fail(`psql exited with code ${res.status} on supabase/${rel}.`)
  }
}

// --- main --------------------------------------------------------------------
loadEnvLocal()
const cmd = process.argv[2]

switch (cmd) {
  case 'bundle':
    bundle()
    break
  case 'rebuild':
    bundle()
    runSql(['rebuild_all.sql'])
    break
  case 'reset':
    runSql(['reset_dev.sql'])
    break
  case 'clear':
    runSql(['clear_dev.sql'])
    break
  case 'fresh':
    bundle()
    runSql(['reset_dev.sql', 'rebuild_all.sql'])
    break
  default:
    fail(`Unknown command "${cmd ?? ''}". Use: bundle | rebuild | reset | clear | fresh`)
}
